Repository nelsonic/github-scraper, pull requests merged in 2024-01, with the labels that each got.

#105 Parse an Issue #103
  lib/issue.js
  lib/scrapers.js
  lib/switcher.js
  test/issue.test.js
Labels: enhancement, help wanted, awaiting-review

#116 Ui update repo
  config/repos.js
  lib/repo.js
  test/repo.test.js
Labels: enhancement

#122 Chore: Fix Scrapers #120
  .github/dependabot.yml
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  README.md
  config/repos.js
  lib/followers.js
  lib/issue.js
  lib/next_page.js
  lib/org.js
  lib/profile.js
  lib/profile_contribs.js
  lib/repo.js
  lib/stars_watchers.js
  lib/switcher.js
  package-lock.json
  package.json
  test/e2e.test.js
  test/followers.test.js
  test/following.test.js
  test/http_request.test.js
  test/issue.test.js
  test/org.test.js
  test/profile.test.js
  test/repo.test.js
  test/stars.test.js
Labels: enhancement, awaiting-review
